const GET_TASK = "GET_TASK";
const CREATE_TASk = "CREATE_TASK";
const UPDATE_TASK = "UPDATE_TASK";
const DELETE_TASK = "DELETE_TASK";
const API_BEGIN = "API_BEGIN";
const API_FAIED = "API_FAILED";

export {
  GET_TASK,
  CREATE_TASk,
  UPDATE_TASK,
  API_FAIED,
  API_BEGIN,
  DELETE_TASK,
};
